version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django-web:
    build: test_task_django_project
    container_name: django-docker
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery_worker:
    build:
      context: ./worker
    command: python -m celery -A tasks worker --loglevel=INFO
    volumes:
      - ./worker:/worker
    depends_on:
      - redis
      - django-web
  celery_beat:
    build:
      context: ./worker
    volumes:
      - ./worker:/worker
    command: python -m celery -A tasks beat --loglevel=INFO
    depends_on:
      - redis
      - django-web
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  postgres_data:
